version: "1.0"

services:
  db_sensors:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=8080
      - POSTGRES_DB=sensors
    ports:
      - "5433:5432"
    networks:
      - microservices-net

  sensor_service:
    restart: always
    build:
      context: monitor-sensors-service
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
    depends_on:
      - db_sensors
      - kafka
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://db_sensors:5432/sensors'
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'kafka:29092'
    networks:
      - microservices-net

  db_statistics:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=8080
      - POSTGRES_DB=statistics
    ports:
      - "5434:5432"
    networks:
      - microservices-net

  statistics_service:
    restart: always
    build:
      context: statistics-service
      dockerfile: Dockerfile
    ports:
      - "8085:8888"
    depends_on:
      - db_statistics
      - sensor_service
      - kafka
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://db_statistics:5432/statistics'
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'kafka:29092'
    networks:
      - microservices-net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - microservices-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
    networks:
      - microservices-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "6060:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge