spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sensors
    username: admin
    password: 8080
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: validate
    open-in-view: false

jwt:
  secret-key: 977edd3d588ad6fa15c9a6396e8a1e5136ebc9eeead755557efb1048c5e3aa3e
  expiration: 3600000 #hour
  refresh-token:
    expiration: 86400000 #a day