--liquibase formatted sql

--changeset david:1
create table sensor
(
    id integer generated by default as identity
        primary key,
    model varchar(255),
    name  varchar(255),
    type  varchar(255),
    unit  varchar(255)
);
--rollback DROP TABLE sensor;

--changeset david:2
create table statistics
(
    id integer generated by default as identity
        primary key,
    count_sensors integer,
    create_date   date,
    statistics_by_type varchar
);
--rollback DROP TABLE statistics;